# Generated by Django 2.2.1 on 2019-06-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('couid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('flag', models.IntegerField()),
                ('maxnum', models.IntegerField(default=40)),
                ('nownum', models.IntegerField(default=0)),
                ('subject', models.ManyToManyField(to='course_selection.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_selection.User')),
                ('name', models.CharField(max_length=10)),
                ('course', models.ManyToManyField(blank=True, null=True, to='course_selection.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_selection.Subject')),
            ],
        ),
    ]
