# Generated by Django 2.2.1 on 2019-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
