# Generated by Django 2.2.1 on 2019-06-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='maxnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='nownum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='course_selection.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_selection.Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
